### ISSUE TITLE
CR-10 Smart Compatibility?

### ISSUE THREAD

**Issue by ShrimpAIO** [Desuuuu/DGUS-reloaded-Klipper#17]
Hello!
The CR-10 Smart printer has just come out, however the firmware on it sucks, so I'm trying to convert it to klipper.
The screen resolution is 800x480, and it's a DMG80480C043_02WTC. 
I've taken a peek at your source code, however the DGUS tools are pretty terrible and there was no clear option or even way in the .CFG files (as it was hex) to recompile the firmware or adjust the screens manually to the correct resolution.
Would you be able to give some pointers on where to look for this as theres little to no documentation that I'm able to find online
Thanks :)

**Comment by Desuuuu** [comment]
That touchscreen has a different resolution and a different architecture than what's supported by this firmware.

To add compatibility for it, you'd need to pretty much remake the touchscreen firmware entirely in the correct format and possibly modify the implementation in Klipper to work with it as well.
