### ISSUE TITLE
2.4 TFT from Longer LK4 / XPT2046

### ISSUE THREAD

**Issue by totynho** [Desuuuu/DGUS-reloaded-Klipper#7]
Hello, i have a longer lk4 with a STM32 MCU. The touchscreen is SID240320-8PCB-D board with XPT2046. If you search XPT2046 in google, you can see this being used directly in raspberry pi, and have many code avaliable. I don't know how hard is to port, but this model aparents to have many documentation in web... Marlin 2.0 with SID240320-8PCB-D configuration is easily found in the web too, i don't know if is possiblle transpile configurations to klipper / DGUS way... Can you look? I'm from Brazil, sorry about my bad english.

**Comment by totynho** [comment]
![1](https://user-images.githubusercontent.com/6473476/112658450-2b3f2680-8e32-11eb-8046-804a9f1b5e17.jpg)
![2](https://user-images.githubusercontent.com/6473476/112658453-2c705380-8e32-11eb-9ae1-c1431f9f840d.jpg)

**Comment by totynho** [comment]
This lcd is used in many models of Longer, Alfawise and Digoo (i don't know if it is digoo)

**Comment by totynho** [comment]
https://github.com/taburyak/STM32-touchscreen-XPT2046-HAL-SPI
https://github.com/topics/xpt2046

i found this, but I really don't know if is useful

**Comment by Desuuuu** [comment]
Sorry but this is completely outside of the scope of this project, which is to add support for DGUS touchscreens.
